### ISSUE TITLE
Split transcoding of single video over multiple nodes

### ISSUE THREAD

**Issue by brunnels** [ccremer/clustercode#9]
It doesn't look like this is currently possible but it would be a nice thing to have.

There's a bash script here that does it with ffmpeg as an example https://github.com/nergdron/dve

**Comment by ccremer** [comment]
I came across dve before. It's an interesting idea. However, it's very difficult to implement. lets call this mode "distributed", and the current model "parallelized" and compare:

1. How would it handle storage? In parallelized mode, each node could potentially be independent and encode only node-local files. Only restriction is file name. In distributed mode, all nodes need access to same storage, so you'll need a clustered or shared filesystem.
2. Since I want to add MongoDB, how would it properly and reliably the ffmpeg output?
3. Error case: Node down. What happens then? Wait for it, continue, abort, ...? It becomes especially difficult when kubernetes is involved.
4. Master election. In distributed mode, there needs to be a master which controls the slave nodes. The current mode doesn't need a master, every node encodes independently. They just need access to a shared state (which nodes encodes what, to prevent duplicate jobs)

You see, it's not easy to implement. Sadly, I currently don't have so much time to implement this. I'd rather focus on the parallelized mode.

**Comment by ccremer** [comment]
I have given much thought about this. I will be implementing this feature in clustercode 2.0, assuming the proof of concept that I am currently working on, actually works.
You can read more about this here: https://github.com/ccremer/clustercode/projects/8

**Comment by jaxjexjox** [comment]
I thought this program might do what the op asked for but alas this post has confirmed it won't speed up a single file.

Your hard work is appreciated none the less, I've googled around and there doesn't seem to be a quick fix to encoding  video across multiple machines,  I thought perhaps considering how long people have been discussing it on the web (Some as early as 2007) maybe someone would've written a great system. Alas, it's quite complicated.

Thanks both of you.     Now if only I could figure out what to do with the small handful of machines I have access to.

**Comment by ccremer** [comment]
Hi @jaxjexjox 
Thanks for you interest in this project.

Quite some time has passed since op opened this issue. At that time, the clustercode was written in Java, however I completely rewrote it from scratch about a year ago and in Go with splitting&merging over multiple machines from the start.

But Alas, it's not finished. Encoding videos over multiple machines "works" if you can run Kubernetes (see https://ccremer.github.io/clustercode-docs/clustercode/explanations/how-it-works.html). But I never made it past a proof-of-concept. Meanwhile, I lack the time and motivation to go on with this project 😞 Maybe the core idea with `ffmpeg -f segment` helps you further.

**Comment by ccremer** [comment]
Clustercode v2 is using the split-encode-merge approach similar to "dve" (new home btw: https://git.sudo.ca/tessa/dve). Closing this.
